{% set version = "1.13.1" %}
{% set number = "0" %}
{% set sha256 = "86fa03133088804ae63e666d560f4f4b5309736094ef0fc50dc1286f6316c81b" %}

package:
  name: biotite
  version: {{ version }}

source:
  url: https://github.com/biotite-dev/biotite/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ number }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: True  # [py < 36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=30.0
    - wheel >=0.30
    - cython >=0.28
    - numpy =1.13  # [py < 37]
    - numpy =1.14  # [py >= 37]
  run:
    - python
    - requests >=2.12
    - {{ pin_compatible('numpy') }}
    - msgpack-python

test:
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - pytest --ignore=tests//application --ignore=tests//database --ignore=tests//test_doctest.py tests

about:
  home: https://www.biotite-python.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: "A comprehensive library for computational molecular biology"
  doc_url: https://www.biotite-python.org/
  dev_url: https://github.com/biotite-dev/biotite

extra:
  recipe-maintainers:
    - padix-key
