{% set version = "0.40.0" %}
{% set number = "0" %}
{% set sha256 = "513179e7549f1e83aabf3753bc51378e9a6ad0679762154b6673634f66b789f9" %}

package:
  name: biotite
  version: {{ version }}

source:
  url: https://github.com/biotite-dev/biotite/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ number }}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py < 310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy <2.0                             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=30.0
    - wheel >=0.30
    - cython >=3.0
    - numpy <2.0
  run:
    - python
    - requests >=2.12
    - {{ pin_compatible('numpy') }}
    - msgpack-python
    - networkx >=2.0

test:
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - pytest --ignore=tests//application --ignore=tests//database --ignore=tests//test_doctest.py tests

about:
  home: https://www.biotite-python.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A comprehensive library for computational molecular biology
  doc_url: https://www.biotite-python.org/
  dev_url: https://github.com/biotite-dev/biotite

extra:
  recipe-maintainers:
    - padix-key
